// Kelime kategorileri
export type WordCategory = "kolay" | "orta" | "zor" | "hayvanlar" | "nesneler" | "meslekler" | "yiyecekler" | "spor"

// Kelime veritabanı
const wordDatabase: Record<WordCategory, string[]> = {
  kolay: [
    "ev",
    "top",
    "göz",
    "el",
    "su",
    "kedi",
    "köpek",
    "kuş",
    "balık",
    "ağaç",
    "çiçek",
    "güneş",
    "ay",
    "yıldız",
    "bulut",
    "yağmur",
    "kar",
    "deniz",
    "dağ",
    "yol",
  ],
  orta: [
    "bilgisayar",
    "telefon",
    "televizyon",
    "araba",
    "bisiklet",
    "uçak",
    "gemi",
    "tren",
    "kitap",
    "kalem",
    "defter",
    "masa",
    "sandalye",
    "kapı",
    "pencere",
    "ayna",
    "saat",
    "çanta",
    "ayakkabı",
    "şapka",
    "gözlük",
    "müzik",
    "film",
    "oyun",
    "spor",
  ],
  zor: [
    "demokrasi",
    "özgürlük",
    "adalet",
    "barış",
    "sevgi",
    "mutluluk",
    "başarı",
    "hayal",
    "gerçek",
    "zaman",
    "mekan",
    "evren",
    "dünya",
    "insan",
    "toplum",
    "kültür",
    "sanat",
    "bilim",
    "teknoloji",
    "ekonomi",
    "politika",
    "tarih",
    "coğrafya",
    "felsefe",
    "din",
  ],
  hayvanlar: [
    "kedi",
    "köpek",
    "kuş",
    "balık",
    "at",
    "inek",
    "koyun",
    "keçi",
    "tavuk",
    "horoz",
    "ördek",
    "kaz",
    "tavşan",
    "fare",
    "aslan",
    "kaplan",
    "fil",
    "zürafa",
    "maymun",
    "ayı",
    "kurt",
    "tilki",
    "sincap",
    "kirpi",
    "kaplumbağa",
    "yılan",
    "timsah",
    "penguen",
    "fok",
    "balina",
  ],
  nesneler: [
    "masa",
    "sandalye",
    "koltuk",
    "yatak",
    "dolap",
    "kitaplık",
    "televizyon",
    "bilgisayar",
    "telefon",
    "saat",
    "lamba",
    "ayna",
    "çerçeve",
    "vazo",
    "tabak",
    "bardak",
    "çatal",
    "kaşık",
    "bıçak",
    "tencere",
    "tava",
    "fırın",
    "buzdolabı",
    "çamaşır makinesi",
    "ütü",
    "süpürge",
    "perde",
    "halı",
    "kilim",
    "battaniye",
    "yastık",
    "yorgan",
    "çarşaf",
    "havlu",
  ],
  meslekler: [
    "öğretmen",
    "doktor",
    "hemşire",
    "mühendis",
    "avukat",
    "hakim",
    "polis",
    "asker",
    "itfaiyeci",
    "pilot",
    "şoför",
    "aşçı",
    "garson",
    "temizlikçi",
    "bahçıvan",
    "terzi",
    "kuaför",
    "marangoz",
    "elektrikçi",
    "tesisatçı",
    "boyacı",
    "inşaatçı",
    "çiftçi",
    "balıkçı",
    "kasap",
    "fırıncı",
    "manav",
    "bakkal",
    "muhasebeci",
    "bankacı",
    "gazeteci",
    "yazar",
    "ressam",
    "müzisyen",
    "oyuncu",
    "yönetmen",
    "fotoğrafçı",
    "tasarımcı",
  ],
  yiyecekler: [
    "ekmek",
    "çorba",
    "pilav",
    "makarna",
    "börek",
    "pizza",
    "hamburger",
    "sandviç",
    "salata",
    "et",
    "tavuk",
    "balık",
    "patates",
    "domates",
    "biber",
    "patlıcan",
    "kabak",
    "havuç",
    "soğan",
    "sarımsak",
    "fasulye",
    "nohut",
    "mercimek",
    "pirinç",
    "bulgur",
    "mısır",
    "elma",
    "armut",
    "portakal",
    "mandalina",
    "limon",
    "çilek",
    "kiraz",
    "üzüm",
    "karpuz",
    "kavun",
    "muz",
    "ananas",
    "şeftali",
    "kayısı",
    "erik",
  ],
  spor: [
    "futbol",
    "basketbol",
    "voleybol",
    "hentbol",
    "tenis",
    "masa tenisi",
    "badminton",
    "golf",
    "beyzbol",
    "kriket",
    "hokey",
    "rugby",
    "amerikan futbolu",
    "boks",
    "güreş",
    "judo",
    "karate",
    "tekvando",
    "eskrim",
    "okçuluk",
    "atıcılık",
    "binicilik",
    "kayak",
    "snowboard",
    "paten",
    "yüzme",
    "dalış",
    "sörf",
    "yelken",
    "kürek",
    "kano",
    "rafting",
    "dağcılık",
    "tırmanış",
    "paraşüt",
    "yamaç paraşütü",
    "koşu",
    "maraton",
    "bisiklet",
    "jimnastik",
    "yoga",
    "pilates",
    "fitness",
    "halter",
    "vücut geliştirme",
  ],
}

// Rastgele kelime seç
export function getRandomWord(category?: WordCategory): string {
  // Kategori belirtilmişse o kategoriden, belirtilmemişse tüm kategorilerden rastgele kelime seç
  if (category) {
    const words = wordDatabase[category]
    return words[Math.floor(Math.random() * words.length)]
  } else {
    // Tüm kategorileri birleştir
    const allWords = Object.values(wordDatabase).flat()
    return allWords[Math.floor(Math.random() * allWords.length)]
  }
}

// Belirli bir zorluk seviyesinden rastgele kelime seç
export function getRandomWordByDifficulty(difficulty: "kolay" | "orta" | "zor"): string {
  const words = wordDatabase[difficulty]
  return words[Math.floor(Math.random() * words.length)]
}

// Belirli kategorilerden rastgele kelime seç
export function getRandomWordFromCategories(categories: WordCategory[]): string {
  // Belirtilen kategorilerdeki tüm kelimeleri birleştir
  const combinedWords = categories.flatMap((category) => wordDatabase[category])
  return combinedWords[Math.floor(Math.random() * combinedWords.length)]
}

// Tüm kategorileri getir
export function getAllCategories(): WordCategory[] {
  return Object.keys(wordDatabase) as WordCategory[]
}

// Belirli bir kategorideki tüm kelimeleri getir
export function getWordsByCategory(category: WordCategory): string[] {
  return wordDatabase[category]
}
